# Site settings
title:       Lui's Blog
email:       levb20@gmail.com
author:      Luis Vasquez
description: "Software Development!, Open Source, Coffee and Beers =)"
disqus_shortname: lvasquez20
url:         http://lvasquez.github.io
timezone: America/Guatemala

# Google Analytics
google_analytics_tracking_id: UA-47464063-1

# Disqus Comments
disqus_short_name: impossiblethoughts
disqus_show_comment_count: true

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: lvasquez
twitter_username: levb20
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/
  
include: [".htaccess"]

BASE_PATH:
